### ISSUE TITLE
Error 0x8013600 - Vegas Pro 14 Release

### ISSUE THREAD

**Issue by Evauation** [RatinFX/VegasProFlow#1]
Good day, I've experienced an issue out of the box that goes as follows.

## Software: Vegas Pro 18 - Windows 10

> System.ApplicationException: Failed to create instance of main class: 'EntryPoint'.
   at ScriptPortal.Vegas.ScriptHost.ScriptManager.Run(Assembly asm, String className, String methodName)
   at ScriptPortal.Vegas.ScriptHost.RunScript(Boolean fCompileOnly)

And I understand that this release is intended for Vegas Pro 14, but I was wondering if this was a compatibility issue or just a bad setup. 

Considering I have taken the precautions to prevent simple issues from occurring on my end. Unblocking DLLs as well as preventing them from being picked up by my antivirus and doing the instructions step by step. Any help would be greatly appreciated. I look forward to this bcuz this seems pretty promising.

**Comment by RatinFX** [comment]
Hello, thank you for writing!

It's my bad, I completely messed up the "How To" section on the release site. It's fixed now and I also added this point to the README.
I rephrased the readme and the Release message as it's supposed to work for all versions `13 and below` or `14 and above`

Please let me know if it works that way!

**Comment by Evauation** [comment]
This has fixed the issue. Although considering from your other work, I didn't consider that the DLLs needed to be placed in Application Extensions.

Regardless, this has fixed it completely and I enjoy it. Depending on usage, I'll be sure to donate for your amazing work ;)

**Comment by RatinFX** [comment]
Yes, this is a "Dockable" application extension that can stay in place after closing it (like my BetterSearch) whereas the other two projects are quick runnable scripts.
Glad to hear it's fixed, hope you enjoy using it 👍
