### ISSUE TITLE
EXE or Manual Install not working on Flow

### ISSUE THREAD

**Issue by composition-cassidy** [RatinFX/VegasProFlow#11]
I've made an Application Extensions folder at %programdata%\VEGAS Pro. %appdata%\VEGAS Pro. %localappdata%\VEGAS Pro. tried .exe and manual installation.. no luck.. what's going on??
<img width="342" alt="image" src="https://github.com/RatinFX/VegasProFlow/assets/99601533/7b28d833-9009-43f4-ad0a-6868a6158773">

**Comment by RatinFX** [comment]
[Please read the readme](https://github.com/RatinFX/VegasProFlow?tab=readme-ov-file#quick-install), it's under `Tools -> Extensions`, not `View`.
