### ISSUE TITLE
Dear RatinFX, can you expand it to Track Motion and Pan&Crop's Mask and Transition Progress Envelop?

### ISSUE THREAD

**Issue by narulmcto** [RatinFX/VegasProFlow#2]
There are three reasons.
1. Track Motion can create 3D camera effects. The animation of 3D camera effects also need Bezier very much.
2. Mask can create Motion Graphics. It also need Bezier very much.
3. Transition Progress also need Bezier very much.

**Comment by RatinFX** [comment]
Hello

1. If you mean Track Pan/Crop: try enabling "Settings - Use Track FX", select the Track, and choose "Pan/Crop" in VPFlow, if not I'd like an example of where can I find this animation.
2. Sadly I didn't find anything about animating Mask related things yet.
3. I'll look into Envelopes if they are doable

**Comment by RatinFX** [comment]
1.4.0 update
1. Added support for Parent Track Motion
2. Sadly, Mask is same as above
3. Added support for some Envelopes (including Transition Progress)
