### ISSUE TITLE
Flow not loading in on VEGAS 14

### ISSUE THREAD

**Issue by mrpapersonic** [RatinFX/VegasProFlow#4]
When I open Vegas upon installing Flow, it doesn't get loaded in:
![image](https://user-images.githubusercontent.com/37962225/236074423-83060d8c-1d4d-4b72-b78e-596e782fc252.png)
It works fine in Vegas 20. Oddly enough, it seems it's accessing the file perfectly fine:
![image](https://user-images.githubusercontent.com/37962225/236074529-9be0b22a-afb6-4ec8-bdbe-56142d7561ce.png)
I'm using Flow 1.0.3 with Vegas 14 on Windows 10 21H2.

**Comment by RatinFX** [comment]
Hello, could you try the newest version?

**Comment by vhoda** [comment]
Yo, you can put the Vegas extensions in the documents folder
![image](https://github.com/RatinFX/VegasProFlow/assets/70240006/14dfe6ea-ac83-42ad-bcf9-849285498540)

**Comment by RatinFX** [comment]
You can place it in many places (mentioned in manual install) and for reasons unknown to me it still did not work for some people
- also moved it from `View` to `Tools`

**Comment by mrpapersonic** [comment]
> Hello, could you try the newest version?
It loads in properly now, thank you!
