### ISSUE TITLE
Vegas pro 20 build 370,402,403 crash when i use the VEGAS PRO FLOW

### ISSUE THREAD

**Issue by sur1to** [RatinFX/VegasProFlow#6]
when i get any error message like "could'nt and ending keyframe for: pan crop" sony vegas crashes (only in vegas pro 20 build 370,402,403)

**Comment by RatinFX** [comment]
Sadly I do not have anything other than VP 14 and 18 to test on, both of these worked fine for me and it seems like only 20 had issues like this for some reason..

**Comment by Zeophoria** [comment]
I have the same issue..

**Comment by Zeophoria** [comment]
> Sadly I do not have anything other than VP 14 and 18 to test on, both of these worked fine for me and it seems like only 20 had issues like this for some reason..

If you want me to provide you with one (not a legit copy but a safe vp 20 build) i can do so and you can run it in a VM just for the sole purpose of debugging this, sounds good?

**Comment by RatinFX** [comment]
should be fixed with 1.4.4 out
